import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar } from "./components/sidebar";
import { connection } from "next/server";
import { ErrorBoundary } from "./error-boundary";
import { getSignedInUserId } from "./actions/session";
import { fetchUsers } from "./actions/users";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connection();
  const currentUserId = await getSignedInUserId();
  const users = await fetchUsers();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <SideBar users={users}  />
          <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">
              <div>Signed In as: {currentUserId}</div>
              {!!currentUserId ? children : <div>Please select a user to sign in.</div>}
            </main>
          </div>
        </ErrorBoundary>
      </body>
    </html>
  );
}
