import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar } from "./components/sidebar";
import { connection } from "next/server";
import { ErrorBoundary } from "./error-boundary";
import { getSignedInUserId } from "./actions/session";
import { fetchUsers } from "./actions/users";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connection();
  const currentUserId = await getSignedInUserId();
  const users = await fetchUsers();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <div className="flex h-screen max-h-screen min-w-full items-center justify-center bg-zinc-50 font-sans ">
            <SideBar users={users} />
            <main className="flex flex-1 h-screen max-h-screen overflow-auto min-h-screen  flex-col items-center justify-between py-32 px-16 bg-white sm:items-start">
              {!!currentUserId ? (
                children
              ) : (
                <div>Please select a user to sign in.</div>
              )}
            </main>
          </div>
        </ErrorBoundary>
      </body>
    </html>
  );
}
